//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiFeed.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MauiFeed.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddFeedButton {
            get {
                return ResourceManager.GetString("AddFeedButton", resourceCulture);
            }
        }
        
        public static string AddFolderLabel {
            get {
                return ResourceManager.GetString("AddFolderLabel", resourceCulture);
            }
        }
        
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        public static string AddToFolderLabel {
            get {
                return ResourceManager.GetString("AddToFolderLabel", resourceCulture);
            }
        }
        
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        public static string AllUnreadLabel {
            get {
                return ResourceManager.GetString("AllUnreadLabel", resourceCulture);
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        public static string DatabaseExportLabel {
            get {
                return ResourceManager.GetString("DatabaseExportLabel", resourceCulture);
            }
        }
        
        public static string DatabaseImportLabel {
            get {
                return ResourceManager.GetString("DatabaseImportLabel", resourceCulture);
            }
        }
        
        public static string DatabaseLabel {
            get {
                return ResourceManager.GetString("DatabaseLabel", resourceCulture);
            }
        }
        
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        public static string DefaultThemeLabel {
            get {
                return ResourceManager.GetString("DefaultThemeLabel", resourceCulture);
            }
        }
        
        public static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        public static string FeedLabel {
            get {
                return ResourceManager.GetString("FeedLabel", resourceCulture);
            }
        }
        
        public static string FeedUrlLabel {
            get {
                return ResourceManager.GetString("FeedUrlLabel", resourceCulture);
            }
        }
        
        public static string FolderLabel {
            get {
                return ResourceManager.GetString("FolderLabel", resourceCulture);
            }
        }
        
        public static string FolderNameLabel {
            get {
                return ResourceManager.GetString("FolderNameLabel", resourceCulture);
            }
        }
        
        public static string GoogleNewsService {
            get {
                return ResourceManager.GetString("GoogleNewsService", resourceCulture);
            }
        }
        
        public static string GoogleSectionBusiness {
            get {
                return ResourceManager.GetString("GoogleSectionBusiness", resourceCulture);
            }
        }
        
        public static string GoogleSectionHealth {
            get {
                return ResourceManager.GetString("GoogleSectionHealth", resourceCulture);
            }
        }
        
        public static string GoogleSectionNation {
            get {
                return ResourceManager.GetString("GoogleSectionNation", resourceCulture);
            }
        }
        
        public static string GoogleSectionScience {
            get {
                return ResourceManager.GetString("GoogleSectionScience", resourceCulture);
            }
        }
        
        public static string GoogleSectionTechnology {
            get {
                return ResourceManager.GetString("GoogleSectionTechnology", resourceCulture);
            }
        }
        
        public static string GoogleSectionWorld {
            get {
                return ResourceManager.GetString("GoogleSectionWorld", resourceCulture);
            }
        }
        
        public static string HideAllReadLabel {
            get {
                return ResourceManager.GetString("HideAllReadLabel", resourceCulture);
            }
        }
        
        public static string JapaneseLanguage {
            get {
                return ResourceManager.GetString("JapaneseLanguage", resourceCulture);
            }
        }
        
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        public static string LightThemeLabel {
            get {
                return ResourceManager.GetString("LightThemeLabel", resourceCulture);
            }
        }
        
        public static string LocalLabel {
            get {
                return ResourceManager.GetString("LocalLabel", resourceCulture);
            }
        }
        
        public static string MarkAllAsReadLabel {
            get {
                return ResourceManager.GetString("MarkAllAsReadLabel", resourceCulture);
            }
        }
        
        public static string MarkAllAsUnrealLabel {
            get {
                return ResourceManager.GetString("MarkAllAsUnrealLabel", resourceCulture);
            }
        }
        
        public static string MarkAsReadLabel {
            get {
                return ResourceManager.GetString("MarkAsReadLabel", resourceCulture);
            }
        }
        
        public static string MarkAsStarLabel {
            get {
                return ResourceManager.GetString("MarkAsStarLabel", resourceCulture);
            }
        }
        
        public static string MarkAsUnreadLabel {
            get {
                return ResourceManager.GetString("MarkAsUnreadLabel", resourceCulture);
            }
        }
        
        public static string MoveToFolderLabel {
            get {
                return ResourceManager.GetString("MoveToFolderLabel", resourceCulture);
            }
        }
        
        public static string NoSelectionLabel {
            get {
                return ResourceManager.GetString("NoSelectionLabel", resourceCulture);
            }
        }
        
        public static string OpenInBrowserLabel {
            get {
                return ResourceManager.GetString("OpenInBrowserLabel", resourceCulture);
            }
        }
        
        public static string OpenShareLabel {
            get {
                return ResourceManager.GetString("OpenShareLabel", resourceCulture);
            }
        }
        
        public static string OPMLFeedLabel {
            get {
                return ResourceManager.GetString("OPMLFeedLabel", resourceCulture);
            }
        }
        
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        public static string RefreshingLabel {
            get {
                return ResourceManager.GetString("RefreshingLabel", resourceCulture);
            }
        }
        
        public static string RemoveFeedLabel {
            get {
                return ResourceManager.GetString("RemoveFeedLabel", resourceCulture);
            }
        }
        
        public static string RemoveFolderLabel {
            get {
                return ResourceManager.GetString("RemoveFolderLabel", resourceCulture);
            }
        }
        
        public static string RemoveFromFolderLabel {
            get {
                return ResourceManager.GetString("RemoveFromFolderLabel", resourceCulture);
            }
        }
        
        public static string RemoveStarLabel {
            get {
                return ResourceManager.GetString("RemoveStarLabel", resourceCulture);
            }
        }
        
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        public static string SmartFeedsLabel {
            get {
                return ResourceManager.GetString("SmartFeedsLabel", resourceCulture);
            }
        }
        
        public static string StarredLabel {
            get {
                return ResourceManager.GetString("StarredLabel", resourceCulture);
            }
        }
        
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        public static string UpdateFolderLabel {
            get {
                return ResourceManager.GetString("UpdateFolderLabel", resourceCulture);
            }
        }
    }
}
